### ISSUE TITLE
compile error related to pthreads on FreeBSD

### ISSUE THREAD

**Issue by ebknudsen** [nexusformat/code#369]
There is a compile error when trying to compile on FreeBSD 10.2
napi.c:111:38: error: use of undeclared identifier 'PTHREAD_MUTEX_RECURSIVE_NP'; did you mean 'PTHREAD_MUTEX_RECURSIVE'?
    pthread_mutexattr_settype(&attr, RECURSIVE_LOCK);
                                     ^~~~~~~~~~~~~~
                                     PTHREAD_MUTEX_RECURSIVE
napi.c:104:24: note: expanded from macro 'RECURSIVE_LOCK'
#define RECURSIVE_LOCK PTHREAD_MUTEX_RECURSIVE_NP
                       ^
/usr/include/pthread.h:130:2: note: 'PTHREAD_MUTEX_RECURSIVE' declared here
        PTHREAD_MUTEX_RECURSIVE         = 2,    /* Recursive mutex */

This is because FreeBSD does not use #defines for pthread constants.
I have a patch for this. Should I do a pull request? Which is preferred?

cheers
Erik

**Comment by eugenwintersberger** [comment]
I Erik
  A pull request would be nice. I assume that you are using autotools for the build. 
In future we will switch to cmake (to avoid maintaining two build systems for NAPI - cmake works well on windows too). Do you have any experience with cmake on FreeBSD?

**Comment by ebknudsen** [comment]
Hi Eugen,
Ok - I'llmake a pull request.
I was using indeed using autotools - I have a little bit of experience using cmake on FreeBSD.
I am part of the McStas/McXtrace team and we switched to cmake a couple of years ago.
Being the only one in the team that runs FreeBSD on a regular basis the work falls to me.

cheers
Erik


On 03/11/15 10:11, Eugen Wintersberger wrote:
> I Erik
> A pull request would be nice. I assume that you are using autotools for
> the build.
> In future we will switch to cmake (to avoid maintaining two build
> systems for NAPI - cmake works well on windows too). Do you have any
> experience with cmake on FreeBSD?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nexusformat/code/issues/369#issuecomment-153293690>.
>

-- 
Erik Bergbäck Knudsen, Research Engineer | DTU | morituri
NEXMAP, DTU Fysik, DK-2800 Kgs. Lyngby, Denmark |<>-<>| te
phone: (+45) 2132 6655 |<>-<>| salutant
