### ISSUE TITLE
fails to build using gcc-4.6

### ISSUE THREAD

**Issue by stuartcampbell** [nexusformat/code#280]
**Original reporter**: _[zjttoefs](https://github.com/zjttoefs)_

```
make[4]: Entering directory `/build/buildd/nexus-4.2-svn1599/applications/NXtranslate/text_collist'
/bin/bash ../../../libtool --tag=CXX   --mode=compile i686-linux-gnu-g++ -DHAVE_CONFIG_H -I. -I../../../include  -I. -I../../../include -fno-common  -g -O2 -fno-strict-aliasing -MT collist_retriever.lo -MD -MP -MF .deps/collist_retriever.Tpo -c -o collist_retriever.lo collist_retriever.cpp
libtool: compile:  i686-linux-gnu-g++ -DHAVE_CONFIG_H -I. -I../../../include -I. -I../../../include -fno-common -g -O2 -fno-strict-aliasing -MT collist_retriever.lo -MD -MP -MF .deps/collist_retriever.Tpo -c collist_retriever.cpp  -fPIC -DPIC -o .libs/collist_retriever.o
In file included from ../retriever.h:6:0,
                 from collist_retriever.h:4,
                 from collist_retriever.cpp:7:
../tree.hh:117:21: error: 'ptrdiff_t' does not name a type
```

Full log see https://launchpadlibrarian.net/75057479/buildlog_ubuntu-oneiric-i386.nexus_4.2-svn1599-3~oneiric1_FAILEDTOBUILD.txt.gz

Known problem: https://wiki.ubuntu.com/GCC4.6
