### ISSUE TITLE
Fails to build with HDF 4.4.0

### ISSUE THREAD

**Issue by sebastic** [nexusformat/code#481]
As reported in [Debian Bug #1146658](https://bugs.debian.org/1146658):
> Your package FTBFS with HDF 4.4.0:
> ```
> /build/nexus-4.4.3/src/napi4.c: In function 'findNapiClass':
> /build/nexus-4.4.3/src/napi4.c:80:3: error: too few arguments to function 'Vgetclass'; expected 3, have 2
>    80 |   Vgetclass(groupID, classText);
>       |   ^~~~~~~~~
> In file included from /usr/include/hdf/hdf.h:192,
>                  from /usr/include/hdf/mfhdf.h:22,
>                  from /build/nexus-4.4.3/include/napi4.h:6,
>                  from /build/nexus-4.4.3/src/napi4.c:39:
> /usr/include/hdf/hproto.h:1407:15: note: declared here
>  1407 | HDFLIBAPI int Vgetclass(int32 vkey, char *vgclass, size_t *buf_size);
>       |               ^~~~~~~~~
> [...]
> /build/nexus-4.4.3/src/napi4.c: In function 'NXIFindVgroup':
> /build/nexus-4.4.3/src/napi4.c:138:9: error: too few arguments to function 'Vgetname'; expected 3, have 2
>   138 |         Vgetname (iNew, pText);
>       |         ^~~~~~~~
> /usr/include/hdf/hproto.h:1405:15: note: declared here
>  1405 | HDFLIBAPI int Vgetname(int32 vkey, char *vgname, size_t *buf_size);
>       |               ^~~~~~~~
> ```
> The full buildlog is attached.
> [nexus_4.4.3-11.1_amd64.build](https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=1146658;filename=nexus_4.4.3-11.1_amd64.build;msg=5)
